# Generated by Django 4.2.10 on 2024-02-21 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
